In [32]:
import numpy as np
import pandas as pd
from io import StringIO

In [78]:
csv_data = """order_id,customer,city,total_bill,tip,table_size
1,Alice,Tel Aviv,45.50,8.00,4
2,Bob,Haifa,22.30,3.50,2
3,Carol,Tel Aviv,67.80,12.00,6
4,David,Jerusalem,15.20,2.00,2
5,Eve,Haifa,89.90,15.00,8
6,Frank,Tel Aviv,33.40,5.50,3
7,Grace,Jerusalem,51.00,9.00,4
8,Henry,Haifa,28.60,4.00,2
9,Iris,Tel Aviv,74.20,13.50,5
10,Jake,Jerusalem,19.80,2.50,2"""

In [79]:
#1 - Load csv_data into a DataFrame using io.StringIO and pd.read_csv. Print .info() and .describe().transpose()
df = pd.read_csv(io('csv_data'))
df = csv_data.strip()

df = pd.read_csv(StringIO(csv_data), sep=',')
display(df)
df.info()
df.describe()
df.transpose()

   order_id customer       city  total_bill   tip  table_size
0         1    Alice   Tel Aviv        45.5   8.0           4
1         2      Bob      Haifa        22.3   3.5           2
2         3    Carol   Tel Aviv        67.8  12.0           6
3         4    David  Jerusalem        15.2   2.0           2
4         5      Eve      Haifa        89.9  15.0           8
5         6    Frank   Tel Aviv        33.4   5.5           3
6         7    Grace  Jerusalem        51.0   9.0           4
7         8    Henry      Haifa        28.6   4.0           2
8         9     Iris   Tel Aviv        74.2  13.5           5
9        10     Jake  Jerusalem        19.8   2.5           2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    10 non-null     int64
 1   customer    10 non-null     object
 2   city        10 non-null     object
 3   total_bill  10 non-null     float64
 4   tip         10 non-null     float64
 5   table_size  10 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 612.0+ bytes

,0,1,2,3,4,5,6,7,8,9
order_id,1,2,3,4,5,6,7,8,9,10
customer,Alice,Bob,Carol,David,Eve,Frank,Grace,Henry,Iris,Jake
city,Tel Aviv,Haifa,Tel Aviv,Jerusalem,Haifa,Tel Aviv,Jerusalem,Haifa,Tel Aviv,Jerusalem
total_bill,45.5,22.3,67.8,15.2,89.9,33.4,51.0,28.6,74.2,19.8
tip,8.0,3.5,12.0,2.0,15.0,5.5,9.0,4.0,13.5,2.5
table_size,4,2,6,2,8,3,4,2,5,2

In [44]:
#2 - Add a column price_per_person that holds the bill divided by the table size, rounded to 2 decimal places.
df['price_per_person'] = (df['total_bill'] / df['table_size']).round(decimals = 2)
df

,order_id,customer,city,total_bill,tip,table_size,price_per_person
0,1,Alice,Tel Aviv,45.5,8.0,4,11.38
1,2,Bob,Haifa,22.3,3.5,2,11.15
2,3,Carol,Tel Aviv,67.8,12.0,6,11.30
3,4,David,Jerusalem,15.2,2.0,2,7.60
4,5,Eve,Haifa,89.9,15.0,8,11.24
5,6,Frank,Tel Aviv,33.4,5.5,3,11.13
6,7,Grace,Jerusalem,51.0,9.0,4,12.75
7,8,Henry,Haifa,28.6,4.0,2,14.30
8,9,Iris,Tel Aviv,74.2,13.5,5,14.84
9,10,Jake,Jerusalem,19.8,2.5,2,9.90

In [55]:
#3 - Filter the DataFrame to show only orders where price_per_person is greater than 12
df = df[df['price_per_person'] > 12]
df

,order_id,customer,city,total_bill,tip,table_size,price_per_person
6,7,Grace,Jerusalem,51.0,9.0,4,12.75
7,8,Henry,Haifa,28.6,4.0,2,14.30
8,9,Iris,Tel Aviv,74.2,13.5,5,14.84

In [69]:
#4 - Use .apply() to create a column table_type: 'Large' if table_size >= 4, otherwise 'Small'
def large(table_size):
    if table_size >= 4:
        return 'Large'
    else:
        return 'Small'
df['table_type'] = df['table_size'].apply(large)
df

C:\Users\liran\AppData\Local\Temp\ipykernel_26408\740265880.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['table_type'] = df['table_size'].apply(large)

,order_id,customer,city,total_bill,tip,table_size,price_per_person,table_type
6,7.0,Grace,Jerusalem,51.0,9.0,4.0,12.75,Large
7,8.0,Henry,Haifa,28.6,4.0,2.0,14.30,Small
8,9.0,Iris,Tel Aviv,74.2,13.5,5.0,14.84,Large
table_type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Small

In [80]:
#5 - Set customer as the index. Then use .loc[] to select the rows from Alice to Carol
df = df.set_index('customer')
df.loc['Alice' : 'Carol']

          order_id      city  total_bill   tip  table_size
customer
Alice            1  Tel Aviv        45.5   8.0           4
Bob              2     Haifa        22.3   3.5           2
Carol            3  Tel Aviv        67.8  12.0           6

In [89]:
#6 - Use pd.concat with axis=0 to create a new DataFrame containing the first 3 rows and the last 3 rows of the original DataFrame. Reset the index
df1 = pd.concat([df.head(3),df.tail(3)], axis = 0)
df1 = df1.reset_index(drop=True)
df1

   order_id       city  total_bill   tip  table_size
0         1   Tel Aviv        45.5   8.0           4
1         2      Haifa        22.3   3.5           2
2         3   Tel Aviv        67.8  12.0           6
3         8      Haifa        28.6   4.0           2
4         9   Tel Aviv        74.2  13.5           5
5        10  Jerusalem        19.8   2.5           2

In [90]:
#7 - Use np.vectorize to create a column value_label: 'High Value' if total_bill > 50 and tip > 10%, otherwise 'Standard'
def check_value(total_bill, tip):
    if total_bill > 50 and tip > (total_bill * 0.1):
        return 'High Value'
    else:
        return 'Standard'

check = np.vectorize(check_value)
df['value_label'] = check(df['total_bill'], df['tip'])
df

          order_id       city  total_bill   tip  table_size value_label
customer
Alice            1   Tel Aviv        45.5   8.0           4    Standard
Bob              2      Haifa        22.3   3.5           2    Standard
Carol            3   Tel Aviv        67.8  12.0           6  High Value
David            4  Jerusalem        15.2   2.0           2    Standard
Eve              5      Haifa        89.9  15.0           8  High Value
Frank            6   Tel Aviv        33.4   5.5           3    Standard
Grace            7  Jerusalem        51.0   9.0           4  High Value
Henry            8      Haifa        28.6   4.0           2    Standard
Iris             9   Tel Aviv        74.2  13.5           5  High Value
Jake            10  Jerusalem        19.8   2.5           2    Standard

In [91]:
#8 - Use .iloc[] to select the last 3 rows of the DataFrame, then use .iloc[] again to select rows at positions 2, 4, and 6
last_3_df = df.iloc[-3:]
last_3_df

          order_id       city  total_bill   tip  table_size value_label
customer
Henry            8      Haifa        28.6   4.0           2    Standard
Iris             9   Tel Aviv        74.2  13.5           5  High Value
Jake            10  Jerusalem        19.8   2.5           2    Standard